<a href="https://colab.research.google.com/github/AadarshU210/Deep-Learning_pytorch_playground/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import numpy as np

In [4]:
my_list = [1,2,3,5,6]
my_list_2d = [[1,2,3,4],[4,6,7,8]]

my_list_2d

[[1, 2, 3, 4], [4, 6, 7, 8]]

In [5]:
np1 = np.random.rand(3,4)
np1.dtype

dtype('float64')

In [6]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 1.0935,  0.1377,  1.7386,  0.3370],
        [-1.0918, -0.1785,  0.0170,  0.3193],
        [-0.4365, -1.2092, -0.1792,  0.4274]])

In [7]:
tensor_2d.dtype

torch.float32

In [8]:
tensors_3d = torch.zeros(2,3,4)
tensors_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
tensor1 = torch.tensor(np1)
tensor1

tensor([[0.8879, 0.4969, 0.3097, 0.9880],
        [0.8648, 0.9005, 0.2518, 0.8865],
        [0.0682, 0.8301, 0.3022, 0.6450]], dtype=torch.float64)

In [10]:
tensor2 = torch.arange(6)
tensor2

tensor([0, 1, 2, 3, 4, 5])

In [11]:
# Reshape and view
tensor2 = tensor2.reshape(3,2)
tensor2

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [12]:
# Reshape if we don't know the number of items using -1

tensor3 = torch.arange(14)
tensor3

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [13]:
tensor3 = tensor3.reshape(2,-1)
tensor3

tensor([[ 0,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12, 13]])

In [14]:
tensor4 = torch.arange(10)
tensor4

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
tensor4 = tensor4.view(2,5)
tensor4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [23]:
# Grab a slice
tensor5 = torch.arange(10)
tensor5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
tensor5 = tensor5.reshape(5,-1)
tensor5

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [26]:
tensor5[1,:]

tensor([2, 3])

In [28]:
# return a column
tensor5[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

Basic math operations in Tensor


In [29]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [30]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [32]:
# Addition longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [33]:
# subtract
tensor_a - tensor_b

tensor([-4, -4, -4, -4])

In [34]:
torch.sub(tensor_a , tensor_b)

tensor([-4, -4, -4, -4])

In [35]:
# multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [36]:
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [37]:
# Division
tensor_a / tensor_b

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [38]:
torch.div(tensor_a, tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [40]:
# Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [41]:
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [42]:
# Exponent / pow

tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

In [43]:
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])